image:
  file: .gitpod.Dockerfile
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
#TODO: github prebuild . ( see gitpod-scheme.json:github)
tasks:

  - name: qemu builder [QEMU BUILD] |
    openMode: split-left
    before:
            git clone https://gitlab.com/qemu-project/qemu.git 
    init:  
             mkdir /workspace/quickemu/qemu/build &&
             cd /workspace/quickemu/qemu/build && 
             ../configure --target-list=x86_64-softmmu && 
             make qemu-system-x86_64  && 
             make qemu-img && 
             sudo ln -s /workspace/quickemu/qemu/build/qemu-system-x86_64 /usr/bin/qemu-system-x86_64 &&
             sudo ln -s /workspace/quickemu/qemu/build/qemu-img /usr/bin/qemu-img &&  
             gp sync-done qemubuilder
    
  - name: pre build [PRE BUILD] |
    openMode: split-left	
    init: echo 'quickemu build ' # runs during prebuild
    before: 
             sudo ln -s /workspace/quickemu/quickemu /usr/bin/quickemu &&
             git clone https://github.com/novnc/noVNC.git &&
             gp sync-done quickemu
    
    command: echo 'YAY'

  - name: running [MAIN] |
    openMode: split-right
    before: echo 'waiting for quickemu preparation'&& gp sync-await quickemu
    init: echo 'waiting for QEMUbuilder  build for finish '&&  gp sync-await qemubuilder
    command: 
            echo 'this will run the envierment cmd after the wait' '&&  gp sync-await qemubuilder && gp sync-await quickemu && 
            ./quickget ubuntu-mate impish && 
            ./quickemu -src /workspace/quickemu/qemu/build/qemu-system-x86_64 --vm ubuntu-mate-impish.conf && 
            ./noVNC/utils/novnc_proxy --vnc :5900 --listen 5959 
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5900
    description: local_vnc
    name: vnc_internal
    onOpen: ignore
    visibility: private
  - port: 5959
    description: novnc
    name: novnc
    onOpen: open-preview
    visibility: private
  - port: 6080
    description: novnc_default
    name: novnc_default
    onOpen: open-preview
    visibility: private
vscode:
  extensions:
    - dracula-theme.theme-dracula
    - ms-azuretools.vscode-docker
    - github.vscode-pull-request-github
