---
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: build
    init: echo 'building from scratch' # runs during prebuild
    before: sudo apt-add-repository -y ppa:flexiondotorg/quickemu &&
             sudo apt -y update &&
             sudo apt -y install quickemu 
  - name: qemu docker
    before: sudo docker pull qemu/x86-64 
    init: sudo 
  - name: qemu builder
    before: git clone https://gitlab.com/qemu-project/qemu.git
    init: mkdir ./qemu/build && cd build && ../configure
    command: make

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
  - port: 5930
vscode:
  extensions:
    - dracula-theme.theme-dracula
