image:
  file: .gitpod.Dockerfile
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
#TODO: github prebuild . ( see gitpod-scheme.json:github)
tasks:

  - name: qemu builder [QEMU BUILD] |
    openMode: split-left
    before:
             git clone https://gitlab.com/qemu-project/qemu.git &&
             mkdir /workspace/quickemu/qemu/build &&
             cd /workspace/quickemu/qemu/build && 
             ../configure --target-list=x86_64-softmmu --enable-debug && 
            make -j$(nproc)
            gp sync-done qemubuilder
    command:  
             
             sudo ln -s /workspace/quickemu/qemu/build/qemu-system-x86_64 /usr/bin/qemu-system-x86_64 &&
             sudo ln -s /workspace/quickemu/qemu/build/qemu-img /usr/bin/qemu-img &&  
             gp sync-done qemubuilder
    
  - name: pre build [PRE BUILD] |
    openMode: split-left	
    
    before: 
             git clone https://github.com/novnc/noVNC.git &&
             gp sync-done novnc
    
    init: echo 'quickemu build ' # runs during prebuild
    command: echo 'YAY'

  - name: running [MAIN] |
    openMode: split-right
    before: 
            echo 'waiting for novnc preparation' && 
            gp sync-await novnc && 
            clear &&
            echo 'DONE'
    init: 
            echo 'quickget - init' &&
            ./quickget ubuntu-mate impish && 
             sudo ln -s /workspace/quickemu/quickemu /usr/bin/quickemu &&
    command: 
            echo 'MAIN task - waiting for qemubuilder...' &&
            gp sync-await qemubuilder &&  
            echo ' done' &&
            ./quickemu --src /workspace/quickemu/qemu/build/ --vm ubuntu-mate-impish.conf && 
            ./noVNC/utils/novnc_proxy --vnc :5900 --listen 5959 
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5900
    description: local_vnc
    name: vnc_internal
    onOpen: ignore
    visibility: private
  - port: 5959
    description: novnc
    name: novnc
    onOpen: open-preview
    visibility: private
  - port: 6080
    description: novnc_default
    name: novnc_default
    onOpen: open-preview
    visibility: private
vscode:
  extensions:
    - dracula-theme.theme-dracula
    - ms-azuretools.vscode-docker
    - github.vscode-pull-request-github
