---
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: build
    init: echo 'building from scratch' # runs during prebuild
    before: sudo apt-add-repository -y ppa:flexiondotorg/quickemu &&
             sudo apt -y update &&
             sudo apt -y install quickemu 

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
vscode:
  extensions:
    - dracula-theme.theme-dracula
