name: Flake ❄️ Checker ✅

on:
  push:
    branches:
      - master
  schedule:
    - cron: '42 0 * * 6'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  flake-checker:
    name: Flake Checker
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

