name: "Lint Shellcheck 🐚"
permissions:
  contents: read

on:
  pull_request:
    branches: '**'
  workflow_dispatch:

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          format: gcc
          severity: warning
