--- # reviewdog
name: reviewdog
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  shellcheck:
    permissions:
      checks: write
      contents: read
      pull-requests: write
    name: github check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haya14busa/action-cond@v1
        id: reporter
        with:
          # Reorters could be: [github-pr-check,github-pr-review,github-check]
          cond: ${{ github.event_name == 'pull_request' }}
          if_true: "github-pr-review"
          if_false: "github-check"
      - uses: reviewdog/action-shellcheck@v1
        with:
          reporter: ${{ steps.reporter.outputs.value }}
          github_token: ${{ secrets.github_token }}
          level: warning
          filter_mode: diff_context # [added,diff_context,file,nofilter]
          shellcheck_flags: --external-sources
          #pattern: |
            #quickget
            #quickemu
          check_all_files_with_shebangs: "true"
