name: Test build quickemu 🚧

on:
  pull_request:
    branches:
      - master
    paths:
      - quickemu
      - quickget
      - debian/**
      - *.nix
  push:
    branches:
      - master
    paths:
      - quickemu
      - quickget
      - debian/**
      - *.nix
  workflow_dispatch:

# TODO: arm64 runner
# https://github.blog/changelog/2024-06-03-actions-arm-based-linux-and-windows-runners-are-now-in-public-beta/

jobs:
  test-deb-build:
    runs-on: ubuntu-22.04
    steps:
    - name: "Checkout 🥡"
      uses: actions/checkout@v4
    - name: "Build & Test .deb 🍥"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sudo apt-get -y update
        sudo apt-get -y install debhelper devscripts
        REL_VER=$(grep "^readonly VERSION" quickemu | cut -d'"' -f2)
        rm debian/changelog
        dch --package quickemu --newversion="${REL_VER}-1" --distribution=unstable "New upstream release." --create
        dpkg-buildpackage --build=binary --no-check-builddeps --compression=gzip
        sudo apt-get -y install ../quickemu_${REL_VER}-1_all.deb
        quickemu --help
        quickget --help

  test-nix-build:
    runs-on: ubuntu-22.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - name: "Checkout 🥡"
        uses: "actions/checkout@v4"
      - name: "Install Nix ❄️"
        uses: "DeterminateSystems/nix-installer-action@v12"
      - name: "Enable Magic Nix Cache 🪄"
        uses: "DeterminateSystems/magic-nix-cache-action@v7"
      - name: "Build & Test .nix ❄️"
        run: |
          nix build .#quickemu
          tree ./result
          ./result/bin/quickemu --help
          ./result/bin/quickget --help

